
name: Github Docker Image CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - run: | 
        docker build -t ghcr.io/james-martinez/chrome-web/chrome-web:latest .
        docker push ghcr.io/james-martinez/chrome-web/chrome-web:latest
